### ISSUE TITLE
Samples are brokered more than once

### ISSUE THREAD

**Issue by kdp-cloud** [elixir-europe/MARS#8]
When submitting to ENA, after submitting to BioSamples, samples are brokered again to BioSample, thus getting again an accession number as is shown in the screenshot.
![image](https://github.com/elixir-europe/MARS/assets/82407142/04a73335-1cb0-4763-834d-c5f73a36f2db)

I'm also not completely sure that both the sources and samples need to get a separate accession number. But this might require so more discussion...

Assuming that asking for ENA not to broker samples to BioSamples is not an option, could it be possible for the ENA web-API to also return the BioSamples accession numbers in the response?

Proposed  solution:
- If ENA is a target repository, submission to Biosamples is skipped.
- Only if ENA is not included in the list of target repositories, then the samples have to be submitted towards BioSamples.

**Comment by apriltuesday** [comment]
ENA submission should allow passing in existing BioSamples accessions, the brokering code should pass these existing accessions to each target repository (perhaps it already does, in which case maybe ENA's conversion service needs to be adjusted). This should maybe be mentioned in the repository service specification.

Otherwise the same issue will occur for many if not all EBI repositories (it certainly will for EVA).

**Comment by bedroesb** [comment]
@kdp-cloud en @apriltuesday i think this is not a problem anymore?

**Comment by kdp-cloud** [comment]
> @kdp-cloud en @apriltuesday i think this is not a problem anymore? 

No this is fixes now...
